apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: guest-login-service
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/preethyvenkat/guest-management-login-microservice.git
    targetRevision: HEAD
    path: helm-chart
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
