apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "guest-login-app.fullname" . }}-config
data:
  LOG_LEVEL: {{ .Values.config.logLevel | quote }}
  WELCOME_MSG: {{ .Values.config.welcomeMsg | quote }}
