apiVersion: apps/v1
kind: Deployment
metadata:
  name: guest-login-service
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: guest-login-service
  template:
    metadata:
      labels:
        app: guest-login-service
      annotations:
      	prometheus.io/scrape: "true"
      	prometheus.io/path: "/metrics"
      	prometheus.io/port: "3000"
    spec:
      containers:
      - name: guest-login-service
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        ports:
        - containerPort: 3000
        resources: {{- toYaml .Values.resources | nindent 10 }}
        env:
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: jwt-secret
              key: secret
        livenessProbe:
          httpGet:
            path: /healthz
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 15
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /healthz
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 10
          timeoutSeconds: 3
          failureThreshold: 3
