#{{- if .Values.keda.enabled }}
#apiVersion: keda.sh/v1alpha1
#kind: ScaledObject
#metadata:
 # name: {{ include "guest-login-app.fullname" . }}
 # namespace: {{ .Release.Namespace }}
#spec:
 # scaleTargetRef:
  #  name: guest-login-app
 # minReplicaCount: {{ .Values.keda.minReplicaCount }}
 # maxReplicaCount: {{ .Values.keda.maxReplicaCount }}
 # triggers:
 #   - type: {{ .Values.keda.cpuTrigger.type }}
  #    metadata:
   #     {{- range $key, $val := .Values.keda.cpuTrigger.metadata }}
    #    {{ $key }}: {{ $val | quote }}
     #   {{- end }}
#{{- end }}



{{- if .Values.keda.enabled }}
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: {{ include "guest-login-app.fullname" . }}
  namespace: {{ .Release.Namespace }}
spec:
  scaleTargetRef:
    name: {{ include "guest-login-app.fullname" . }}
  minReplicaCount: {{ .Values.keda.minReplicaCount }}
  maxReplicaCount: {{ .Values.keda.maxReplicaCount }}
  triggers:
    - type: prometheus
      metadata:
        serverAddress: {{ .Values.keda.prometheus.serverAddress | quote }}
        metricName: {{ .Values.keda.prometheus.metricName | quote }}
        threshold: {{ .Values.keda.prometheus.threshold | quote }}
        query: {{ .Values.keda.prometheus.query | quote }}
{{- end }}
