apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ include "guest-login-service.fullname" . }}-log-agent
  labels:
    app: {{ include "guest-login-service.name" . }}-log-agent
spec:
  selector:
    matchLabels:
      app: {{ include "guest-login-service.name" . }}-log-agent
  template:
    metadata:
      labels:
        app: {{ include "guest-login-service.name" . }}-log-agent
    spec:
      serviceAccountName: signoz-log-agent
      containers:
      - name: signoz-log-agent
        image: signoz/signoz-log-agent:latest
        imagePullPolicy: Always
        resources:
          limits:
            memory: 200Mi
            cpu: 200m
          requests:
            memory: 100Mi
            cpu: 100m
        env:
        - name: OTEL_EXPORTER_OTLP_ENDPOINT
          value: http://signoz-otel-collector.platform.svc.cluster.local:4317
        - name: LOG_LEVEL
          value: "info"
        volumeMounts:
        - name: varlog
          mountPath: /var/log
        - name: varlibdockercontainers
          mountPath: /var/lib/docker/containers
          readOnly: true
      volumes:
      - name: varlog
        hostPath:
          path: /var/log
      - name: varlibdockercontainers
        hostPath:
          path: /var/lib/docker/containers
