name: Install Prometheus and KEDA

on:
  workflow_dispatch:

jobs:
  install-monitoring:
    #runs-on: ubuntu-latest
    runs-on: self-hosted
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Update kubeconfig
        run: |
          aws eks update-kubeconfig --region ${{ secrets.AWS_REGION }} --name ${{ secrets.EKS_CLUSTER_NAME }}

      - name: Install Prometheus (DaemonSet)
        run: |
          helm repo add prometheus-community https://prometheus-community.github.io/helm-charts
          helm repo update
          helm upgrade --install prometheus prometheus-community/prometheus \
            -n monitoring --create-namespace \
            --set alertmanager.enabled=false \
            --set pushgateway.enabled=false \
            --set server.enabled=false \
            --set nodeExporter.enabled=true \
            --set kubeStateMetrics.enabled=true \
            --set prometheus-node-exporter.service.type=ClusterIP

      - name: Install KEDA using Helm
        run: |
          helm repo add kedacore https://kedacore.github.io/charts
          helm repo update
          helm upgrade --install keda kedacore/keda \
            --namespace keda --create-namespace
